Problem 3 -> Part 1] Generating Data
Generate N observations from a normal distribution: data = randn(N, 1); This will generate N 1-D samples with mean equal to 0 and variance equal to 1.

In [1]:
import pandas as pd
import numpy as np

Following funtion generateObservation(), generates n 1-D observation with mean = 0 and variance = 1.

In [2]:
def generateObservation(n):
  observation = np.random.normal(0, 1, n)
  return observation

In [3]:
generateObservation(20) # will produce 20 random observations, wit

array([ 1.83004009, -0.90411785, -1.7535462 ,  1.84753376, -0.81888012,
        0.73807049, -0.68048846, -2.00569954,  0.92536707, -0.42406544,
       -1.82828456,  1.1590259 , -0.51032593, -0.61276737, -1.22681026,
       -0.38547289, -1.7430956 ,  0.08785469, -0.19462303, -0.20767364])

Estimate the mean and variance of the data for N = 10, 100, 1000 etc.

In [4]:
def generateObservation(n):
  observation = np.random.normal(0, 1, n)
  return observation

Estimating mean and variance

In [5]:
n = input("Enter the number of observation : ")
m = np.mean(generateObservation(int(n)))
v = np.var(generateObservation(int(n)))
f"mean = {m} and variance = {v}"

Enter the number of observation : 20


'mean = 0.26981162019873145 and variance = 0.5598831989863875'

Estimating mean and variance for N = 10

In [6]:
m1 = np.mean(generateObservation(10))
f"mean = {m1}"

'mean = -0.0532551688203746'

In [7]:
v1 = np.var(generateObservation(10))
f"variance = {v1}"

'variance = 0.33502494300165353'

Estimating mean and variance for N = 100

In [8]:
m2 = np.mean(generateObservation(100))
f"mean = {m2}"

'mean = 0.0249890753567679'

In [9]:
v2 = np.var(generateObservation(100))
f"variance = {v2}"

'variance = 0.9626802503715755'

Estimating mean and variance for N = 1000

In [10]:
m3 = np.mean(generateObservation(1000))
f"mean = {m3}"
v3 = np.var(generateObservation(1000))
f"variance = {v3}"

'variance = 0.9863749548670236'

Modify the code so that the generated data have mean and variance equal to user-speciJed parameters mean and var.

In [11]:
import math
def generateData(m, variance):
  sigma = math.sqrt(variance)
  return np.random.normal(m, sigma, 1000)

Please pass the mean and variance of your choice as the arguments for generateData() function. (This function gives 1000 observation)


In [12]:
generateData(500, 5)

array([498.89438616, 497.44605789, 503.03054785, 503.45589908,
       500.60741563, 500.4186644 , 503.92602387, 500.4788072 ,
       500.25830966, 499.01221051, 497.23896826, 497.80820209,
       500.07394337, 501.45167208, 499.80357575, 497.51898386,
       498.25892722, 504.62238674, 499.53190668, 497.06222308,
       498.40606702, 501.00772861, 502.62073228, 498.46499559,
       502.45012393, 499.84568067, 501.35189203, 499.45520675,
       500.56887018, 501.79773609, 498.58514107, 499.04528285,
       497.07173758, 504.73400171, 500.25920495, 497.22545379,
       498.64874472, 499.1880452 , 498.28588814, 498.63685254,
       500.82612115, 500.86880748, 499.68087568, 502.50743048,
       498.41102626, 498.784819  , 500.96186263, 498.31670763,
       498.79495666, 499.97988603, 501.57287178, 499.77803035,
       500.01151005, 498.4379285 , 501.30584419, 500.17404437,
       502.26751647, 499.81662349, 502.60530119, 495.53864264,
       500.44332784, 499.4675025 , 501.08537922, 502.72

Following function will generate 1000 observation with the user-speciJed parameters mean and variance

In [13]:
import math
def generateYourData():
  m = input("Enter mean : ")
  sigma = input("Enter variance : ")
  def generateData(m, variance):
    sigma = math.sqrt(variance)
    return np.random.normal(m, sigma, 1000)
  return generateData(int(m), int(sigma))

call the function generateYourData()

In [14]:
generateYourData()

Enter mean : 10
Enter variance : 5


array([11.47707921,  4.48737329,  8.36991282, 10.84805304,  7.77666533,
       10.12325721, 12.1837712 ,  9.91876896,  7.37699917,  8.78192274,
        8.39341996,  9.38863976, 11.38391986, 11.3084534 ,  9.93855272,
        9.83022031,  7.38661455, 14.02984442, 10.98974001,  7.2689016 ,
       10.4596925 ,  9.83272342,  8.15309583,  9.2681075 , 11.89954096,
        9.60379302,  9.14373055, 12.04778081, 11.23690178, 10.11227734,
       11.22682796, 10.44298908,  9.68194383, 12.92077625, 11.33089404,
       10.27389194, 12.27802163,  9.72365585, 10.89686719, 10.21591728,
       10.53612934, 13.14863464, 10.80723117, 12.9539474 , 10.54007446,
        5.99729569,  7.92591761,  9.36668151,  8.85609116, 10.65695762,
       11.39286264, 11.60177337, 11.63839576, 13.36472247, 11.62978389,
        8.11899072,  9.50491743, 10.05434699,  7.56236944, 12.34225059,
       11.30180852,  8.78179436,  7.71026727,  8.43806482,  6.64753452,
       10.55078485, 11.02706699,  9.17987311,  8.70922341,  7.72

Problem 3. Part 2] Veri8cation

In [15]:
import math
def generateData(m, variance, n):
  sigma = math.sqrt(variance)
  return np.random.normal(m, sigma, n)

In [16]:
np.mean(generateData(1, 4, 2000))

0.9412195741936101

In [17]:
np.var(generateData(1, 4, 2000))

4.099210707878874

In [18]:
np.mean(generateData(4, 9, 1000))

3.9585459307271003

In [19]:
np.var(generateData(4, 9, 1000))

8.997455747874374

For the combined data the mean and variance is very close to theorically calculated combined mean and combined variance

In [20]:
np.mean(generateData(2, 7.67, 3000))

1.9769536207473029

np.var(generateData(2, 7.67, 3000))

We can see that the mean and the variance of the combined data is very close to the value we have calculated.
Which is: mean = 2 variance = 7.6667